version: '3.4'

services:
  bookapi:
    image: ${DOCKER_REGISTRY-}bookapi
    build:
      context: .
      dockerfile: BookAPI/Dockerfile

    environment:
        ConnectionStrings__DefaultConnection: "Server=db,1433; Database=BookData; User Id=sa; Password=Password1!;"
    ports:
      - "5000:80"
    depends_on:
      - db

  db: 
    image: "mcr.microsoft.com/mssql/server"
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "Password1!"
        ACCEPT_EULA: "Y"